/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c CarAdaptor -a CarAdaptor.h:CarAdaptor.cpp ../car.xml -i ../CustomType.h
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "CarAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CarAdaptor
 */

CarAdaptor::CarAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CarAdaptor::~CarAdaptor()
{
    // destructor
}

StringMapList CarAdaptor::speed(int ini)
{
    // handle method call com.soulxu.dbus.qt.car.speed
    StringMapList outp;
    QMetaObject::invokeMethod(parent(), "speed", Q_RETURN_ARG(StringMapList, outp), Q_ARG(int, ini));
    return outp;
}

int CarAdaptor::startup()
{
    // handle method call com.soulxu.dbus.qt.car.startup
    int isok;
    QMetaObject::invokeMethod(parent(), "startup", Q_RETURN_ARG(int, isok));
    return isok;
}

void CarAdaptor::stop()
{
    // handle method call com.soulxu.dbus.qt.car.stop
    QMetaObject::invokeMethod(parent(), "stop");
}

DoubleInt CarAdaptor::test()
{
    // handle method call com.soulxu.dbus.qt.car.test
    DoubleInt dii;
    QMetaObject::invokeMethod(parent(), "test", Q_RETURN_ARG(DoubleInt, dii));
    return dii;
}

DoubleIntList CarAdaptor::test1()
{

    // handle method call com.soulxu.dbus.qt.car.test1
    DoubleIntList adii;
    QMetaObject::invokeMethod(parent(), "test1", Q_RETURN_ARG(DoubleIntList, adii));
    emit stoped(adii);
    return adii;
}

