all: hannota permutation subsetsum stairs

hannota: hannota.cc
	g++ hannota.cc -o hannota

permutation: permutation.cc
	g++ permutation.cc -o permutation

subsetsum: subsetsum.cc
	g++ subsetsum.cc -o subsetsum

stairs: stairs.cc
	g++ stairs.cc -o stairs
