#!/bin/bash

CONF_FILE="/etc/xen-server-address.conf"
ADDR=""
TARGET_DIR="/usr/share/xenlogin"

if [ $# -eq 1 ]; then
	ADDR=$1
else 
	if [ -e $CONF_FILE ]; then
		ADDR=`cat $CONF_FILE`
	fi
fi

if [ $ADDR == "" ]; then
	echo "Can not find server address."
	exit 1;
fi

xulrunner "$TARGET_DIR/application.ini" "$ADDR"
