Document: systemhelper
Title: Debian systemhelper Manual
Author: <insert document author here>
Abstract: This manual describes what systemhelper is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/systemhelper/systemhelper.sgml.gz

Format: postscript
Files: /usr/share/doc/systemhelper/systemhelper.ps.gz

Format: text
Files: /usr/share/doc/systemhelper/systemhelper.text.gz

Format: HTML
Index: /usr/share/doc/systemhelper/html/index.html
Files: /usr/share/doc/systemhelper/html/*.html
