Document: xenlogin
Title: Debian xenlogin Manual
Author: <insert document author here>
Abstract: This manual describes what xenlogin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xenlogin/xenlogin.sgml.gz

Format: postscript
Files: /usr/share/doc/xenlogin/xenlogin.ps.gz

Format: text
Files: /usr/share/doc/xenlogin/xenlogin.text.gz

Format: HTML
Index: /usr/share/doc/xenlogin/html/index.html
Files: /usr/share/doc/xenlogin/html/*.html
