/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c CarAdaptor -a CarAdaptor.h:CarAdaptor.cpp car.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CARADAPTOR_H_1277881739
#define CARADAPTOR_H_1277881739

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.soulxu.dbus.qt.car
 */
class CarAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.soulxu.dbus.qt.car")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.soulxu.dbus.qt.car\">\n"
"    <method name=\"startup\"/>\n"
"    <method name=\"stop\"/>\n"
"    <signal name=\"stoped\"/>\n"
"  </interface>\n"
        "")
public:
    CarAdaptor(QObject *parent);
    virtual ~CarAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void startup();
    void stop();
Q_SIGNALS: // SIGNALS
    void stoped();
};

#endif
